spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: vitalii
    password: p@sword
    driver-class-name: org.postgresql.Driver
  batch:
    initialize-schema: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: vitalii.nedbaliuk@globallogic.com
    password: weRtsM!-02a
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true